#!/usr/bin/env python3
"""Generate docs/PLATFORM_YAML.md from the pydantic models in
infra_utils/platform_config.py.

The models are the schema; this renders them so the reference can never
disagree with what the validator accepts. Prose lives in DESCRIPTIONS below
(field comments in the model are not introspectable); a field without an
entry renders as TODO and tests/test_platform_reference.py fails on it.
Presets are embedded verbatim, so reference and presets cannot drift.

    gen_platform_reference.py          # write docs/PLATFORM_YAML.md
    gen_platform_reference.py --check  # exit 1 with a diff if it is stale
"""

from __future__ import annotations

import difflib
import sys
import types
import typing
from pathlib import Path

from pydantic import BaseModel
from pydantic_core import PydanticUndefined

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from infra_utils import platform_config as pc

OUT = ROOT / "docs" / "PLATFORM_YAML.md"
PRESETS = ROOT / "presets"
FOOTER = "<!-- generated by scripts/gen_platform_reference.py — do not edit by hand -->"
TODO = "TODO"

# Dotted key → prose. Written from the model comments, README's config table
# and docs/. Keep it "why", the table already says "what".
DESCRIPTIONS: dict[str, str] = {
    "project": "Name prefix for every stack, role and SSM parameter (`{project}-{environment}-…`). Changing it is a new deployment, not a rename.",
    "environment": "Second half of the stack prefix; lets one account hold `dev` and `prod` side by side.",
    "region": "Where everything deploys. Also decides whether `gateway.web_search: auto` turns on (launch regions only).",
    "use_cases": "Opt-in use cases: name → that use case's own config block, passed to its `build()` untouched (`{}` enables with defaults). Names must exist under `use-cases/`, so a typo is an error, not a silent no-op. Their stacks ride at the end of the footprint.",
    # deployment
    "deployment.mode": "`workshop` keeps disposable lifecycle defaults. `production` retains stateful resources and fails validation unless enterprise identity, networking, audit, authorization, guardrails, model allow-listing and monitored alarms are all configured.",
    "deployment.strategy": "`centralized` puts everything in one account. `distributed` means each team deploys its own copy of this file. `federated` splits shared services (auth, gateway) into `platform_account` from agent runtimes in `workload_accounts`; the account you deploy into decides the role, the same file works in both.",
    "deployment.platform_account": "12-digit account this deployment may modify. Required for production and for centralized/distributed enterprise-IdP deployments; in a federated deployment it hosts the shared services.",
    "deployment.workload_accounts": "12-digit accounts that run agent runtimes in a `federated` deployment. Deploying a federated file from an account in neither list is a hard error.",
    "deployment.federation.gateway_url": "Platform-account gateway MCP endpoint a workload account calls (an output of the platform gateway stack).",
    "deployment.federation.issuer_url": "Platform Cognito issuer; the OIDC discovery URL is derived from it.",
    "deployment.federation.m2m_client_id": "Platform Cognito M2M client id the workload's token vault exchanges for a JWT. Not secret.",
    "deployment.federation.m2m_client_secret_name": "Secrets Manager NAME in the workload account holding the M2M client secret. The secret itself never goes in this file.",
    # identity
    "identity.idp": "Who authenticates users. `cognito` is self-contained; the others federate Cognito to your enterprise IdP (docs/ENTERPRISE_IDP.md).",
    "identity.mode": "Who issues the tokens. `brokered`: Cognito issues them and the IdP only signs users in — works with no IdP at all. `direct`: the IdP issues them and no Cognito user pool is deployed; `entra_id` only, and the app registration needs a service principal and v2 access tokens (docs/ENTERPRISE_IDP.md, Direct mode).",
    "identity.tenant_id": "Entra ID tenant. Required when `idp: entra_id`.",
    "identity.client_id": "App registration / OIDC client id at your IdP.",
    "identity.issuer_url": "OIDC issuer of your IdP. Required for `okta` and `ping` (Entra derives it from the tenant).",
    "identity.client_secret_name": "Secrets Manager NAME holding the IdP client secret. Required for any non-Cognito IdP; the value never goes in this file.",
    # agents
    "agents.pattern": "Which agent container the runtime stack builds (docs/ARCHITECTURE.md). Ignored for the image once `migration:` is set, but still exported so verify and invoke behave.",
    "agents.model_id": "Bedrock model or cross-region inference profile injected as `MODEL_ID` into every agent. Empty = each pattern's baked-in default.",
    "agents.allowed_models": "Model allow-list. When set, the runtime roles' Bedrock IAM is scoped to exactly these and `model_id` must be one of them (otherwise the containers' defaults would bypass the list). Empty = unrestricted, today's behaviour.",
    "agents.a2a": "Deploy the `code-agent` and `research-agent` sub-agent runtimes next to the orchestrator (A2A protocol).",
    "agents.orchestrator_runtime_generation": "Controlled replacement generation for the orchestrator AgentCore Runtime. Increase only when an existing runtime is unreadable or another immutable runtime property requires replacement; healthy A2A runtimes are unaffected.",
    "agents.memory.long_term": "Add the semantic long-term strategy to the AgentCore Memory store (fact extraction across sessions).",
    "agents.memory.event_expiry_days": "How long AgentCore Memory events remain available. Production requires an explicit bounded value and retains the Memory resource itself on stack deletion.",
    "agents.memory.top_k": "Long-term retrieval: how many records to pull per query.",
    "agents.memory.relevance_score": "Long-term retrieval: minimum relevance for a record to be returned.",
    # gateway
    "gateway.web_search": "Built-in web-search connector on the gateway. `auto` turns it on only in regions where the connector exists.",
    "gateway.tools": "Lambda tool names the gateway exposes. Schema-validated today; the deployed list still comes from `tool_configs` in `app.py` (docs/modules/gateway.md).",
    # security
    "security.networking": "VPC mode: runtimes in private subnets behind a NAT gateway and VPC endpoints. Adds the `networking` stack; required by migration private dependencies.",
    "security.cloudtrail_alerting": "The `security` stack: a CloudTrail trail plus alerting. Needed for `traceability` to fire at all.",
    "security.resource_policies": "In-account-only resource policy on the Memory store, with an org deny guard. Needs `org_id`.",
    "security.egress_filter": "Bedrock Guardrail plus an interceptor Lambda on the gateway; masks PII in tool traffic rather than blocking it (docs/SECURITY_CONTROLS.md).",
    "security.require_guardrails": "IAM-denies Bedrock inference without a Guardrail on the runtime roles, creates a baseline guardrail per runtime and injects it into the agents. Incompatible with the `claude-sdk-*` patterns, which cannot attach one.",
    "security.cedar.enabled": "Cedar policy engine on the gateway (tool-level authorization).",
    "security.cedar.mode": "`LOG_ONLY` records decisions without enforcing; flip to `ENFORCE` only after reading the logs on live traffic.",
    "security.traceability": "SNS + EventBridge alerts on sensitive API calls. Requires `cloudtrail_alerting`, the rule only matches CloudTrail management events.",
    "security.org_id": "AWS Organizations id (`o-…`) the VPC endpoint and Memory policies are scoped to. Empty is fine (deploy.sh prompts); a placeholder is rejected.",
    # observability
    "observability.transaction_search": "Configure CloudWatch Transaction Search so runtime traces are searchable. Account-scoped, not per stack.",
    "observability.alarms": "CloudWatch alarms per deployed resource, an SNS ops topic and the platform dashboard.",
    "observability.alarm_email": "Inbox subscribed to the alarm topic (SNS sends a confirmation first). Empty = topic without subscription; placeholders are rejected.",
    "observability.log_retention_days": "CloudWatch log retention for platform-managed log groups. Supported values map to native CloudWatch periods: 30, 90, 180, or 365 days.",
    # migration
    "migration": "Move an existing agent onto the platform. Absent = no migration, everything behaves as before. Stack names do not change: the migrated agent deploys as `…-runtime-orchestrator` on both targets.",
    "migration.source.platform": "Where the agent runs today. Shapes the docs and the plan, not the deploy.",
    "migration.source.image": "Pre-built image reference. Exactly one of `image` or `build`. AgentCore Runtime is arm64-only and a pre-built image cannot be checked for that before deploy, so the plan warns.",
    "migration.source.build": "Build the image here from the customer's Dockerfile. Yields arm64 by construction, which is why the shipped preset uses it. Exactly one of `image` or `build`.",
    "migration.source.build.context": "Docker build context, relative to the repo root.",
    "migration.source.build.dockerfile": "Dockerfile path, relative to `context`.",
    "migration.source.registry_secret_name": "Secrets Manager NAME holding docker-login credentials for a private registry.",
    "migration.source.port": "What the container listens on. Required by the supported `adapter` mode.",
    "migration.source.invoke_path": "Where the container takes a request. Required by the supported adapter mode, which forwards `POST /invocations` there.",
    "migration.source.health_path": "What the adapter polls to answer `GET /ping`.",
    "migration.source.trigger": "How work arrives today. Discovery metadata only: trigger and cutover infrastructure are external and are not deployed.",
    "migration.source.env": "Plain configuration for the container. Secret-shaped keys (`*_SECRET`, `*_TOKEN`, `*_KEY`, …) are refused because env values render in clear.",
    "migration.source.secrets": "Environment variable NAMES only. Each value lives in Secrets Manager under `<project>/<environment>/migration/<NAME>`; the plan lists what to create.",
    "migration.target.runtime": "Only `agentcore` is currently deployable (arm64, the 8080 `/invocations` contract). `ec2` is reserved for a future ECS-on-EC2 implementation and fails validation.",
    "migration.target.mode": "Only `adapter` is currently deployable; it wraps the container so it speaks the AgentCore contract. `native` is reserved for a future implementation and fails validation.",
    "migration.network.private_dependencies": "Up to 25 unique customer-side hostnames (3,000 encoded bytes) the agent must still reach. Needs `security.networking` and a `connectivity` other than `none`; verification runs a fixed allow-list TLS probe from the runtime VPC.",
    "migration.network.connectivity": "Records the existing external path from the platform VPC to the customer network. The accelerator does not provision VPN or Transit Gateway resources.",
    "migration.network.dns_forwarders": "Records externally managed IPv4 resolvers for private hostnames. The accelerator does not create resolver endpoints or rules.",
    "migration.network.ca_bundle_secret_name": "Secrets Manager NAME of a private CA bundle used by the network probe. The bundle is read in memory and is not injected into the customer image or returned as evidence.",
    "migration.network.receipt.vpc_id": "Deployed target VPC ID containing the runtime and fixed dependency probe. Required before private-network approval.",
    "migration.network.receipt.private_subnet_ids": "Deployed private subnet IDs used by the dependency probe; the digest sorts them because order has no meaning.",
    "migration.network.receipt.security_group_ids": "Deployed security group IDs used by the dependency probe; the digest sorts them because order has no meaning.",
    "migration.network.receipt.ca_bundle_version_id": "Exact Secrets Manager version ID of the tested private CA bundle. Required when `ca_bundle_secret_name` is set, so rotation invalidates approval.",
    "migration.network.receipt.probe_verification_reference": "Customer evidence reference for the successful fixed allow-list DNS and hostname-verified TLS probe from the deployed VPC.",
    "migration.stages.runtime.account_id": "12-digit AWS account containing the verified AgentCore Runtime and its VPC. Required for cutover; must match the Runtime ARN and deployment account intent.",
    "migration.stages.runtime.runtime_arn": "AgentCore Runtime ARN captured from the deployed runtime stack. Required for cutover and checked against the configured account and Region.",
    "migration.stages.runtime.source_hash": "The 16-character `SourceHash` output from the deployed runtime stack, binding approval to the reviewed source and migration adapter build.",
    "migration.stages.runtime.image_digest": "Immutable ECR image digest (`sha256:…`) resolved after deployment; a mutable image tag is not sufficient cutover evidence.",
    "migration.stages.runtime.verification_reference": "Customer evidence reference for the successful live `deploy.sh verify` run against this exact deployed target.",
    "migration.stages.data.strategy": "`none` keeps data movement out of scope. `retain-source` uses versioned retain-source dataset contracts. `external-copy` records and gates a separately designed customer procedure; neither strategy runs a copy during deployment.",
    "migration.stages.data.datasets": "Up to 25 versioned retain-source dataset contracts. Each names a declared private dependency plus customer-approved classification, retention, identity-mapping, and validation references.",
    "migration.stages.triggers.strategy": "`none` leaves the source trigger unchanged. `external-shadow` records and gates a customer-operated shadow rehearsal; the accelerator does not create or change the event source.",
    "migration.stages.triggers.source_reference": "Reference to the current event source or route. Must differ from `shadow_reference`; use an identifier, not a payload or credential.",
    "migration.stages.triggers.shadow_reference": "Reference to the separate disabled, dry-run, idempotent, or dual-published shadow target used for rehearsal.",
    "migration.stages.triggers.safety_mode": "How shadow work avoids customer impact. HTTP/webhook: `read-only` or `idempotent`; schedule: `dry-run` or `idempotent`; queue: `dual-publish` to a separate destination.",
    "migration.stages.triggers.idempotency_reference": "Customer evidence for duplicate detection/idempotency. Required for `idempotent` and `dual-publish` safety modes.",
    "migration.stages.triggers.signature_validation_reference": "Customer evidence that webhook signatures are validated before processing. Required for webhook shadowing.",
    "migration.stages.triggers.validation_reference": "Customer test or result reference proving the shadow path accepted representative events without unsafe effects.",
    "migration.stages.traffic.strategy": "`none` means safe target-only deployment. `external-canary` records percentage steps for HTTP/webhook routing. `external-switch` records an atomic customer-operated switch and is required for schedule/queue cutover.",
    "migration.stages.traffic.router_reference": "Reference to the customer-owned router, event-source configuration, or approved change that will perform the shift.",
    "migration.stages.traffic.source_reference": "Reference to the recorded rollback destination. Must differ from `target_reference`.",
    "migration.stages.traffic.target_reference": "Reference to the reviewed AgentCore target route or event-source destination.",
    "migration.stages.traffic.metrics_reference": "Dashboard or query reference used to evaluate every step against the abort thresholds.",
    "migration.stages.traffic.canary_steps_percent": "For `external-canary`, one to ten unique increasing percentages from 1 through 100, ending at 100. Forbidden for an atomic switch.",
    "migration.stages.traffic.abort": "Required customer-approved stop conditions evaluated during every canary step or atomic-switch observation window.",
    "migration.stages.traffic.abort.max_error_rate_percent": "Maximum acceptable error rate from 0 through 100 before rollback.",
    "migration.stages.traffic.abort.max_p95_latency_ms": "Maximum acceptable p95 latency in milliseconds before rollback.",
    "migration.stages.traffic.abort.max_failed_events": "Maximum acceptable failed event count before rollback.",
    "migration.stages.traffic.abort.observation_minutes": "How long to observe each step before proceeding, from 1 minute through 24 hours.",
}

for _gate_prefix in (
    "migration.network.gate",
    "migration.stages.runtime.gate",
    "migration.stages.data.gate",
    "migration.stages.triggers.gate",
    "migration.stages.traffic.gate",
):
    DESCRIPTIONS.update(
        {
            f"{_gate_prefix}.owner": "Team or alias accountable for executing and reversing this stage.",
            f"{_gate_prefix}.approver": "Separate team or alias that accepted the referenced evidence.",
            f"{_gate_prefix}.approved_at": "Non-future timestamp with UTC offset. Supplying it asserts final approval and requires every other gate field; traffic approval must not predate any required prerequisite.",
            f"{_gate_prefix}.expires_at": "Required UTC-offset timestamp after approval and no more than seven days later. An expired gate blocks readiness.",
            f"{_gate_prefix}.evidence": "One or more references in the customer's approved evidence system; do not paste payloads or secrets. Runtime, network, data, trigger, and traffic gates also require their exact printed plan digest.",
            f"{_gate_prefix}.rollback": "Concise reversal procedure or reference. Required before the gate can pass.",
        }
    )

# Dotted key → the name to_env() emits for it. Checked against a fully
# populated to_env() at generation time so this cannot drift from the code.
ENV: dict[str, str] = {
    "project": "PROJECT_NAME",
    "environment": "ENVIRONMENT",
    "region": "AWS_REGION",
    "deployment.mode": "DEPLOYMENT_MODE",
    "deployment.strategy": "DEPLOYMENT_STRATEGY",
    "deployment.platform_account": "PLATFORM_ACCOUNT",
    "identity.idp": "IDP_TYPE",
    "identity.mode": "IDP_MODE",
    "identity.tenant_id": "IDP_TENANT_ID",
    "identity.client_id": "IDP_CLIENT_ID",
    "identity.issuer_url": "IDP_ISSUER_URL",
    "identity.client_secret_name": "IDP_CLIENT_SECRET_NAME",
    "agents.pattern": "AGENT_PATTERN",
    "agents.model_id": "MODEL_ID",
    "agents.allowed_models": "ALLOWED_MODELS",
    "agents.a2a": "ENABLE_A2A",
    "agents.orchestrator_runtime_generation": "ORCHESTRATOR_RUNTIME_GENERATION",
    "agents.memory.long_term": "USE_LONG_TERM_MEMORY",
    "agents.memory.event_expiry_days": "MEMORY_EVENT_EXPIRY_DAYS",
    "agents.memory.top_k": "LTM_TOP_K",
    "agents.memory.relevance_score": "LTM_RELEVANCE_SCORE",
    "gateway.web_search": "ENABLE_WEB_SEARCH",
    "security.networking": "ENABLE_NETWORKING",
    "security.cloudtrail_alerting": "ENABLE_SECURITY",
    "security.resource_policies": "ENABLE_RESOURCE_POLICIES",
    "security.egress_filter": "ENABLE_EGRESS_FILTER",
    "security.require_guardrails": "REQUIRE_GUARDRAILS",
    "security.cedar.enabled": "ENABLE_CEDAR",
    "security.cedar.mode": "CEDAR_MODE",
    "security.traceability": "ENABLE_TRACEABILITY",
    "security.org_id": "ORG_ID",
    "observability.transaction_search": "ENABLE_TRANSACTION_SEARCH",
    "observability.alarms": "ENABLE_ALARMS",
    "observability.alarm_email": "ALARM_EMAIL",
    "observability.log_retention_days": "LOG_RETENTION_DAYS",
    "migration": "MIGRATION_ENABLED",
    "migration.source.platform": "MIGRATION_SOURCE_PLATFORM",
    "migration.source.image": "MIGRATION_SOURCE_IMAGE",
    "migration.source.build.context": "MIGRATION_BUILD_CONTEXT",
    "migration.source.build.dockerfile": "MIGRATION_BUILD_DOCKERFILE",
    "migration.source.registry_secret_name": "MIGRATION_REGISTRY_SECRET_NAME",
    "migration.source.port": "MIGRATION_PORT",
    "migration.source.invoke_path": "MIGRATION_INVOKE_PATH",
    "migration.source.health_path": "MIGRATION_HEALTH_PATH",
    "migration.source.trigger": "MIGRATION_TRIGGER",
    "migration.source.env": "MIGRATION_ENV_JSON",
    "migration.source.secrets": "MIGRATION_SECRETS",
    "migration.target.runtime": "MIGRATION_TARGET_RUNTIME",
    "migration.target.mode": "MIGRATION_TARGET_MODE",
    "migration.network.private_dependencies": "MIGRATION_PRIVATE_DEPENDENCIES",
    "migration.network.connectivity": "MIGRATION_CONNECTIVITY",
    "migration.network.dns_forwarders": "MIGRATION_DNS_FORWARDERS",
    "migration.network.ca_bundle_secret_name": "MIGRATION_CA_BUNDLE_SECRET_NAME",
}

# Temporarily emitted for app.py/runtime_stack.py compatibility, but omitted
# from the reference so new integrations adopt the lossless JSON transport.
LEGACY_ENV = {"MIGRATION_ENV"}

# Keys whose value changes WHICH stacks expected_stacks() returns (not just
# how a stack is configured). Read from expected_stacks() by hand.
FOOTPRINT = {
    "deployment.strategy",
    "agents.a2a",
    "security.networking",
    "security.cloudtrail_alerting",
    "use_cases",
}

# Every to_env() key populated, so the ENV table above is checked against the
# code rather than trusted. Satisfies every cross-field validator on purpose.
_FULL = {
    "deployment": {
        "strategy": "federated",
        "platform_account": "111111111111",
        "workload_accounts": ["222222222222"],
    },
    "identity": {
        "idp": "entra_id",
        # Real-shaped values: the placeholder rules (feat/design-placeholders)
        # refuse sentinels, and this fixture must keep validating after they land.
        "tenant_id": "3f2b1c4d-5e6f-4a7b-8c9d-0e1f2a3b4c5d",
        "client_id": "9a8b7c6d-1234-4abc-9def-000111222333",
        "issuer_url": "https://login.microsoftonline.com/3f2b1c4d/v2.0",
        "client_secret_name": "agentcore/idp-client-secret",
    },
    "agents": {
        "model_id": "us.anthropic.claude-sonnet-4-6",
        "allowed_models": ["us.anthropic.claude-sonnet-4-6"],
        "orchestrator_runtime_generation": 2,
    },
    "security": {
        "networking": True,
        "cloudtrail_alerting": True,
        "traceability": True,
        "org_id": "o-abcdefghij",
    },
    "observability": {"alarm_email": "ops@corp.internal"},
    "migration": {
        "source": {
            "platform": "openshift",
            "build": {"context": "."},
            "registry_secret_name": "r",
            "port": 8000,
            "invoke_path": "/run",
            "env": {"LOG_LEVEL": "info"},
            "secrets": ["JIRA_TOKEN"],
        },
        "network": {
            "private_dependencies": ["jira.corp.internal"],
            "connectivity": "vpn",
            "dns_forwarders": ["10.0.0.2"],
            "ca_bundle_secret_name": "ca",
        },
    },
}


# ── schema walk ──


def _is_model(t: object) -> bool:
    return isinstance(t, type) and issubclass(t, BaseModel)


def _unwrap_optional(t: object) -> tuple[object, bool]:
    """`X | None` → (X, True); anything else → (t, False)."""
    if typing.get_origin(t) in (typing.Union, types.UnionType):
        args = [a for a in typing.get_args(t) if a is not type(None)]
        if len(args) == 1:
            return args[0], True
    return t, False


def _type_str(t: object, field) -> str:
    t, optional = _unwrap_optional(t)
    origin = typing.get_origin(t)
    if origin is typing.Literal:
        out = "one of: " + ", ".join(f"`{a}`" for a in typing.get_args(t))
    elif origin is list:
        out = f"list of {_type_str(typing.get_args(t)[0], None)}"
    elif origin is dict:
        k, v = typing.get_args(t)
        out = f"map of {_type_str(k, None)} → {_type_str(v, None)}"
    elif _is_model(t):
        out = "block"
    elif t is dict:
        out = "object"
    else:
        out = getattr(t, "__name__", str(t))
    if field is not None:
        out += _constraints(field)
    return out + (", optional" if optional else "")


def _constraints(field) -> str:
    lo = hi = None
    bits = []
    for m in field.metadata:
        lo = getattr(m, "ge", lo)
        hi = getattr(m, "le", hi)
        if getattr(m, "pattern", None):
            bits.append(f"matches `{m.pattern}`")
        if getattr(m, "min_length", None):
            bits.append(f"at least {m.min_length}")
    if lo is not None or hi is not None:
        bits.insert(0, f"{lo if lo is not None else ''}–{hi if hi is not None else ''}")
    return f" ({'; '.join(bits)})" if bits else ""


def _default_str(field) -> str:
    if field.default_factory is not None:
        v = field.default_factory()
    elif field.default is PydanticUndefined:
        return "**required**"
    elif field.default is None:
        return "absent"
    else:
        v = field.default
    return '`""`' if v == "" else f"`{v!r}`"


def walk(model: type[BaseModel], prefix: str = "") -> list[dict]:
    """Leaf rows in declaration order. A nested block gets a row of its own
    only when it is optional (absence means something); required blocks
    appear through their leaves."""
    rows: list[dict] = []
    for name, field in model.model_fields.items():
        key = f"{prefix}{name}"
        inner, optional = _unwrap_optional(field.annotation)
        if _is_model(inner):
            if optional:
                rows.append(_row(key, field))
            rows.extend(walk(inner, key + "."))
        else:
            rows.append(_row(key, field))
    return rows


def _row(key: str, field) -> dict:
    return {
        "key": key,
        "type": _type_str(field.annotation, field),
        "default": _default_str(field),
        "env": ENV.get(key, ""),
        "desc": DESCRIPTIONS.get(key, TODO),
        "footprint": key in FOOTPRINT,
    }


def sections(model: type[BaseModel]) -> list[tuple[str, list[dict]]]:
    """One section per top-level block; root scalars go first as 'Top level'."""
    rows = walk(model)
    blocks = [
        n
        for n, f in model.model_fields.items()
        if _is_model(_unwrap_optional(f.annotation)[0])
    ]
    out = [
        (
            "Top level",
            [r for r in rows if "." not in r["key"] and r["key"] not in blocks],
        )
    ]
    for name in blocks:
        out.append((name, [r for r in rows if r["key"].split(".")[0] == name]))
    return out


# ── consistency guards (raise: a wrong reference must not be writable) ──


def check_env_table(model: type[BaseModel]) -> None:
    # source.image and source.build are mutually exclusive, so ONE manifest can
    # never emit both env names: take the union of the two shapes.
    import copy

    with_image = copy.deepcopy(_FULL)
    with_image["migration"]["source"].pop("build")
    with_image["migration"]["source"]["image"] = "registry.example.com/team/agent:1"
    emitted = set(pc.to_env(model.model_validate(_FULL))) | set(
        pc.to_env(model.model_validate(with_image))
    )
    listed = set(ENV.values()) | LEGACY_ENV
    if emitted != listed:
        raise SystemExit(
            f"ENV table drifted from to_env(): missing={sorted(emitted - listed)} "
            f"stale={sorted(listed - emitted)}"
        )


def check_description_keys(model: type[BaseModel]) -> list[str]:
    keys = {r["key"] for r in walk(model)}
    stale = sorted((set(DESCRIPTIONS) | set(ENV) | FOOTPRINT) - keys)
    if stale:
        raise SystemExit(f"generator tables name keys the model does not have: {stale}")
    return sorted(k for k in keys if k not in DESCRIPTIONS)


# ── render ──

INTRO = """\
# platform.yaml reference

`platform.yaml` is the one file that describes a deployment: project identity,
account strategy, IdP, agent pattern, gateway tools, security controls,
observability, and (for a migration) the agent you are bringing. Everything
else — the stack list, verification, the dashboard, destroy — is derived from
it, so a typo'd key is an error and every failure in the file is reported at
once.

You rarely write it from scratch: `deploy.sh design --profile <name>` writes it
from the matching `presets/<name>.yaml` (the presets are embedded verbatim at
the end of this page). Edit the result, then validate without touching AWS:

```bash
python -m infra_utils.platform_config platform.yaml
```

Precedence when a value is set in more than one place:
`cdk context > env var > platform.yaml > defaults`. The **Env override**
column is the name `to_env()` exports for each key — the same name `deploy.sh`
and `app.py` read, so an exported variable wins over the file for that run
only. Keys marked ✦ change **which stacks** are deployed
(`expected_stacks()`), not just how a stack is configured; a plan is printed
before anything is created.
"""

LEGEND = (
    "✦ changes the deployment footprint (the set of stacks), see `expected_stacks()`."
)


def _table(rows: list[dict]) -> list[str]:
    out = [
        "| Key | Type | Default | Env override | Description |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        key = f"`{r['key']}`" + (" ✦" if r["footprint"] else "")
        env = f"`{r['env']}`" if r["env"] else "—"
        out.append(f"| {key} | {r['type']} | {r['default']} | {env} | {r['desc']} |")
    return out


def render(model: type[BaseModel] = pc.PlatformConfig, presets: Path = PRESETS) -> str:
    check_env_table(model)
    check_description_keys(model)
    lines = [INTRO, LEGEND, ""]
    for title, rows in sections(model):
        heading = title if title == "Top level" else f"`{title}:`"
        doc = _block_doc(model, title)
        lines += [f"## {heading}", ""]
        if doc:
            lines += [doc, ""]
        lines += _table(rows) + [""]
    lines += [
        "## Presets",
        "",
        "Each preset is a complete, validated `platform.yaml`; `--profile <name>` copies it for you.",
        "",
    ]
    for p in sorted(presets.glob("*.yaml")):
        lines += [
            "<details>",
            f"<summary><code>presets/{p.name}</code></summary>",
            "",
            "```yaml",
            p.read_text().rstrip("\n"),
            "```",
            "",
            "</details>",
            "",
        ]
    lines += [FOOTER, ""]
    return "\n".join(lines)


def _block_doc(model: type[BaseModel], name: str) -> str:
    """First paragraph of a block model's docstring, if it has one."""
    field = model.model_fields.get(name)
    if field is None:
        return ""
    inner, _ = _unwrap_optional(field.annotation)
    doc = (inner.__doc__ or "").strip()
    if not doc or doc.startswith("Usage docs:"):  # pydantic's BaseModel default
        return ""
    return " ".join(doc.split("\n\n")[0].split())


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current == text:
            return 0
        sys.stdout.writelines(
            difflib.unified_diff(
                current.splitlines(True),
                text.splitlines(True),
                str(OUT.relative_to(ROOT)),
                "generated",
            )
        )
        print(
            f"\n{OUT.relative_to(ROOT)} is stale; run scripts/gen_platform_reference.py"
        )
        return 1
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
